apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testing
  annotations:
    github.com/project-slug: Abhay-soni-developer/testing
spec:
  type: website
  lifecycle: development
  owner: Abhay-soni-developer
